#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WEAR_APP_DIR="$REPO_ROOT/apps/wear-os-app"
WEAR_ENV_FILE="$WEAR_APP_DIR/.env.local"
DEFAULT_API_URL='https://buenahora.com/api/metrics/location'

mkdir -p "$WEAR_APP_DIR"

if [[ -z "${INFISICAL_ENV:-}" ]]; then
  export INFISICAL_ENV='dev'
fi
export INFISICAL_ENABLED='true'

KEY_VALUE="$(
  cd "$REPO_ROOT"
  bash ./scripts/with-infisical.sh bash -lc 'printf "%s" "${LOCATION_METRICS_WEBHOOK_KEY:-}"'
)"

if [[ -z "$KEY_VALUE" ]]; then
  echo "LOCATION_METRICS_WEBHOOK_KEY is empty. Check Infisical auth/project/env first." >&2
  exit 1
fi

API_URL="${LOCATION_METRICS_API_URL:-$DEFAULT_API_URL}"

escaped_key="${KEY_VALUE//\\/\\\\}"
escaped_key="${escaped_key//\"/\\\"}"

{
  echo '# Generated by scripts/wear/pull-location-metrics-key.sh'
  echo '# Refresh with: pnpm --filter @corphish/wear-os-app secret:pull'
  printf 'LOCATION_METRICS_WEBHOOK_KEY="%s"\n' "$escaped_key"
  printf 'LOCATION_METRICS_API_URL=%s\n' "$API_URL"
} >"$WEAR_ENV_FILE"

chmod 600 "$WEAR_ENV_FILE" 2>/dev/null || true

echo "Wrote cached wear env to $WEAR_ENV_FILE"
